apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-operators-redhat-
  name: openshift-operators-redhat
  namespace: openshift-operators-redhat
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  upgradeStrategy: Default
