apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
stringData:
  access_key_id: '{{aws.access_key_id}}}'
  access_key_secret: '{{aws.access_key_secret}}'
  bucketnames: s3-bucket-loki-logs
  endpoint: 'https://s3.{{aws.region}}.amazonaws.com'
  region: '{{aws.region}}'