apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3-todo
  namespace: openshift-logging
stringData:
  access_key_id: '{{AWS_ACCESS_KEY_ID}}}'
  access_key_secret: '{{AWS_SECRET_ACCESS_KEY}}'
  bucketnames: s3-bucket-loki-logs
  endpoint: 'https://s3.us-east-2.amazonaws.com'
  region: 'us-east-2'